### ISSUE TITLE
Incorrect xpath for element attributes

### ISSUE THREAD

**Issue by 8bitgentleman** [karlicoss/backup-goodreads#2]
I noticed that several of the GR review options were not being parsed correctly by the DAL because they are element attributes not text inside an element. This is especially true when a book/review is on multiple shelves

This
https://github.com/karlicoss/goodrexport/blob/dfcbdc0234da990c5b663c4eabf0e91dcedb979f/dal.py#L56

Should be this:
```
shelves = []
for s in r.xpath('shelves/shelf'):
    shelves.append(s.attrib['name'])
```

**Comment by karlicoss** [comment]
Hey, good catch, thanks!
Haven't noticed this before since I don't use shelves personally. I checked the XMLs, and don't think there are any other properties with similar problem?

P.S. ugh, github autoclosed the issue, but anyway feel free to reopen if you think there are any other issues.

**Comment by 8bitgentleman** [comment]
None that I saw. There are several attributes that you aren't pulling from the xml, like rating, but the ones you pull seen to work 👍
